[all_nodes]
phoenix-node-control-plane ansible_host=79.72.10.194 ansible_host_private=10.0.1.79 node_private_ip=10.0.1.79 k3s_server_private_ip=10.0.1.79 kubernetes_node_name=controlplane k3s_server_extra_args="--node-ip 10.0.1.79 --advertise-address 10.0.1.79 --tls-san 127.0.0.1 --tls-san 10.0.1.79"
phoenix-node-app ansible_host=81.208.190.96 ansible_host_private=10.0.1.120 node_private_ip=10.0.1.120 kubernetes_node_name=app k3s_agent_extra_args="--node-ip 10.0.1.120"
phoenix-node-observatory ansible_host=130.110.126.37 ansible_host_private=10.0.1.233 node_private_ip=10.0.1.233 kubernetes_node_name=observatory k3s_agent_extra_args="--node-ip 10.0.1.233"
phoenix-node-ai-ops ansible_host=130.110.108.152 ansible_host_private=10.0.1.245 node_private_ip=10.0.1.245 kubernetes_node_name=aiops k3s_agent_extra_args="--node-ip 10.0.1.245"
phoenix-node-ollama ansible_host=193.122.74.169 ansible_host_private=10.0.1.184 node_private_ip=10.0.1.184 kubernetes_node_name=ollama k3s_agent_extra_args="--node-ip 10.0.1.184"

[control_plane]
phoenix-node-control-plane

[workers]
phoenix-node-app
phoenix-node-observatory
phoenix-node-ai-ops
phoenix-node-ollama

[app]
phoenix-node-app

[observability]
phoenix-node-observatory

[observatory]
phoenix-node-observatory

[ai_ops]
phoenix-node-ai-ops

[ollama]
phoenix-node-ollama

[all_nodes:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
k3s_server_host=phoenix-node-control-plane
k3s_control_plane_private_ip=10.0.1.79
k3s_expected_local_tunnel=127.0.0.1:6443

