apiVersion: v1
kind: Service
metadata:
  name: banking-app-service
  namespace: bankapp
  labels:
    app.kubernetes.io/name: banking-app-service
    app.kubernetes.io/part-of: bankapp
    app.kubernetes.io/component: backend-compat
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: banking-backend
  ports:
    - name: http
      port: 80
      targetPort: http
