apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - mysql-pvc.yaml
  - mysql-service.yaml
  - mysql-deployment.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-compat-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
