apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bankapp-mysql-data
  namespace: bankapp
  labels:
    app.kubernetes.io/name: bankapp-mysql
    app.kubernetes.io/part-of: bankapp
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
