apiVersion: v1
kind: Secret
metadata:
  name: bankapp-secret
  namespace: bankapp
  labels:
    app.kubernetes.io/name: bankapp
    app.kubernetes.io/part-of: bankapp
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:mysql://dummy-rds-private-endpoint:3306/dummy_bankapp
  SPRING_DATASOURCE_USERNAME: dummy-user
  SPRING_DATASOURCE_PASSWORD: dummy-password-change-before-deploy
  JWT_SECRET: dummy-jwt-secret-change-before-deploy
