apiVersion: v1
kind: Secret
metadata:
  name: bankapp-secret
  namespace: bankapp
  labels:
    app.kubernetes.io/name: bankapp
    app.kubernetes.io/part-of: bankapp
type: Opaque
stringData:
  BANKAPP_DB_USERNAME: dummy-user
  BANKAPP_DB_PASSWORD: dummy-password-change-before-deploy
  BANKAPP_API_TOKEN: dummy-token-change-before-deploy
