apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: observability
type: Opaque
stringData:
  admin-user: dummy-admin
  admin-password: dummy-change-me
