apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: observability
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: false
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki:3100
        editable: false
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: Phoenix-Ops
        orgId: 1
        folder: Phoenix-Ops
        type: file
        disableDeletion: true
        editable: false
        options:
          path: /var/lib/grafana/dashboards
