from __future__ import annotations

from app.remediation.models import CatalogEntry


def load_catalog() -> dict[str, CatalogEntry]:
    entries = [
        CatalogEntry(
            remediation_id="restart_banking_backend",
            description="Perform a bounded rollout restart for deployment/banking-backend in namespace bankapp and verify rollout health.",
            allowed_namespaces=["bankapp"],
            allowed_resource_kinds=["Deployment"],
            allowed_resource_names=["banking-backend"],
            risk_class="low",
            blast_radius="low",
            rollback_capability="snapshot_only",
            required_evidence=["deployment_status", "restart_count"],
            verification_checks=["rollout_status", "deployment_readiness", "restart_stability"],
            cooldown_minutes=30,
            timeout_seconds=120,
            required_approval_level="operator",
            executable=True,
        ),
        CatalogEntry(
            remediation_id="restart_failed_pod",
            description="Catalog placeholder for pod restart handling. Not executable in this phase.",
            allowed_namespaces=["bankapp"],
            allowed_resource_kinds=["Pod"],
            allowed_resource_names=[],
            risk_class="low",
            blast_radius="low",
            rollback_capability="snapshot_only",
            required_evidence=["restart_count"],
            verification_checks=["pod_ready"],
            cooldown_minutes=30,
            timeout_seconds=60,
            required_approval_level="operator",
            executable=False,
        ),
        CatalogEntry(
            remediation_id="pause_rollout",
            description="Catalog placeholder for pausing a rollout after human review.",
            allowed_namespaces=["bankapp"],
            allowed_resource_kinds=["Deployment"],
            allowed_resource_names=["banking-backend"],
            risk_class="medium",
            blast_radius="medium",
            rollback_capability="snapshot_only",
            required_evidence=["deployment_status"],
            verification_checks=["rollout_status"],
            cooldown_minutes=60,
            timeout_seconds=60,
            required_approval_level="senior_operator",
            executable=False,
        ),
        CatalogEntry(
            remediation_id="resume_rollout",
            description="Catalog placeholder for resuming a paused rollout after human review.",
            allowed_namespaces=["bankapp"],
            allowed_resource_kinds=["Deployment"],
            allowed_resource_names=["banking-backend"],
            risk_class="medium",
            blast_radius="medium",
            rollback_capability="snapshot_only",
            required_evidence=["deployment_status"],
            verification_checks=["rollout_status"],
            cooldown_minutes=60,
            timeout_seconds=60,
            required_approval_level="senior_operator",
            executable=False,
        ),
        CatalogEntry(
            remediation_id="rollback_previous_revision",
            description="Catalog placeholder for rollout undo after rollback automation is implemented.",
            allowed_namespaces=["bankapp"],
            allowed_resource_kinds=["Deployment"],
            allowed_resource_names=["banking-backend"],
            risk_class="medium",
            blast_radius="medium",
            rollback_capability="planned_future",
            required_evidence=["deployment_status", "rollout_history"],
            verification_checks=["rollout_status"],
            cooldown_minutes=60,
            timeout_seconds=120,
            required_approval_level="incident_commander",
            executable=False,
        ),
    ]
    return {entry.remediation_id: entry for entry in entries}
