from __future__ import annotations

from app.remediation.models import CatalogEntry


def load_catalog() -> dict[str, CatalogEntry]:
    entries = [
        CatalogEntry(
            remediation_id="restart_deployment",
            description="Perform a bounded rollout restart for a deployment and verify rollout health.",
            allowed_namespaces=["bankapp"],
            allowed_resource_kinds=["Deployment"],
            risk_class="low",
            blast_radius="low",
            rollback_capability="snapshot_only",
            required_evidence=["deployment_status", "restart_count"],
            verification_checks=["rollout_status", "readiness"],
            cooldown_minutes=30,
            timeout_seconds=120,
            required_approval_level="operator",
            executable=True,
        ),
        CatalogEntry(
            remediation_id="restart_failed_pod",
            description="Catalog placeholder for pod restart handling. Not executable until a safe bounded verb exists.",
            allowed_namespaces=["bankapp"],
            allowed_resource_kinds=["Pod"],
            risk_class="low",
            blast_radius="low",
            rollback_capability="snapshot_only",
            required_evidence=["restart_count"],
            verification_checks=["pod_ready"],
            cooldown_minutes=30,
            timeout_seconds=60,
            required_approval_level="operator",
            executable=False,
        ),
        CatalogEntry(
            remediation_id="pause_rollout",
            description="Catalog placeholder for pausing a rollout after human review.",
            allowed_namespaces=["bankapp"],
            allowed_resource_kinds=["Deployment"],
            risk_class="medium",
            blast_radius="medium",
            rollback_capability="snapshot_only",
            required_evidence=["deployment_status"],
            verification_checks=["rollout_status"],
            cooldown_minutes=60,
            timeout_seconds=60,
            required_approval_level="senior_operator",
            executable=False,
        ),
        CatalogEntry(
            remediation_id="resume_rollout",
            description="Catalog placeholder for resuming a paused rollout after human review.",
            allowed_namespaces=["bankapp"],
            allowed_resource_kinds=["Deployment"],
            risk_class="medium",
            blast_radius="medium",
            rollback_capability="snapshot_only",
            required_evidence=["deployment_status"],
            verification_checks=["rollout_status"],
            cooldown_minutes=60,
            timeout_seconds=60,
            required_approval_level="senior_operator",
            executable=False,
        ),
        CatalogEntry(
            remediation_id="rollback_previous_revision",
            description="Catalog placeholder for rollout undo after rollback automation is implemented.",
            allowed_namespaces=["bankapp"],
            allowed_resource_kinds=["Deployment"],
            risk_class="medium",
            blast_radius="medium",
            rollback_capability="planned_future",
            required_evidence=["deployment_status", "rollout_history"],
            verification_checks=["rollout_status"],
            cooldown_minutes=60,
            timeout_seconds=120,
            required_approval_level="incident_commander",
            executable=False,
        ),
        CatalogEntry(
            remediation_id="cordon_node",
            description="Bounded node cordon candidate for future policy-approved node isolation.",
            allowed_namespaces=["bankapp"],
            allowed_resource_kinds=["Node"],
            risk_class="medium",
            blast_radius="medium",
            rollback_capability="uncordon_node",
            required_evidence=["node_pressure"],
            verification_checks=["node_schedulable"],
            cooldown_minutes=120,
            timeout_seconds=60,
            required_approval_level="incident_commander",
            executable=True,
        ),
        CatalogEntry(
            remediation_id="uncordon_node",
            description="Bounded node uncordon candidate for recovery of previously isolated nodes.",
            allowed_namespaces=["bankapp"],
            allowed_resource_kinds=["Node"],
            risk_class="medium",
            blast_radius="medium",
            rollback_capability="cordon_node",
            required_evidence=["node_pressure"],
            verification_checks=["node_schedulable"],
            cooldown_minutes=120,
            timeout_seconds=60,
            required_approval_level="incident_commander",
            executable=True,
        ),
        CatalogEntry(
            remediation_id="clear_stuck_job",
            description="Catalog placeholder for known-safe stuck job handling after bounded delete semantics are designed.",
            allowed_namespaces=["bankapp"],
            allowed_resource_kinds=["Job"],
            risk_class="medium",
            blast_radius="low",
            rollback_capability="snapshot_only",
            required_evidence=["job_state"],
            verification_checks=["job_progress"],
            cooldown_minutes=60,
            timeout_seconds=60,
            required_approval_level="operator",
            executable=False,
        ),
    ]
    return {entry.remediation_id: entry for entry in entries}
