[all_nodes]
control-plane ansible_host=13.53.32.8 ansible_host_private=10.0.1.174 k3s_server_private_ip=10.0.1.174
observatory-node ansible_host=51.20.119.13
app-node ansible_host=51.20.78.13
ollama-node ansible_host=51.20.255.205
ai-ops ansible_host=13.49.75.204

[control_plane]
control-plane

[workers]
observatory-node
app-node
ollama-node
ai-ops

[observatory]
observatory-node

[app]
app-node

[ollama]
ollama-node

[ai_ops]
ai-ops

[all_nodes:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/banking-app.pem
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
