[all_nodes]
control-plane ansible_host=51.21.245.193 ansible_host_private=10.0.1.131 k3s_server_private_ip=10.0.1.131
observatory-node ansible_host=13.60.14.230
app-node ansible_host=13.51.55.90
ollama-node ansible_host=13.48.84.59
ai-ops ansible_host=13.61.186.167

[control_plane]
control-plane

[workers]
observatory-node
app-node
ollama-node
ai-ops

[observatory]
observatory-node

[app]
app-node

[ollama]
ollama-node

[ai_ops]
ai-ops

[all_nodes:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/banking-app.pem
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
